name: Docker Image CI

on:
  push:
    branches:
      - "create_image"
      - "main"
    paths:
      - "Dockerfile"

jobs:
  build:
    if: github.ref == 'create_image'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cs_rankings_image

  build_publish:
    if: github.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:
      - docker build . --file Dockerfile --tag ghcr.io/debruijn/cs_rankings_image
      - docker push ghcr.io/debruijn/cs_rankings_image:latest
